import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {
  SidebarNotifyProvider,
  SidebarProvider,
  TabSelectProvider,
} from "@/shared/context/aside";
import { Toaster } from "@/components/ui/toaster";
import { LoadingProvider } from "@/shared/context/loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head />
      <body>
        <LoadingProvider>
          <SidebarNotifyProvider>
            <SidebarProvider>
              <TabSelectProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem
                  disableTransitionOnChange
                >
                  <div className="w-full flex">
                    {children}
                    <Toaster />
                  </div>
                </ThemeProvider>
              </TabSelectProvider>
            </SidebarProvider>
          </SidebarNotifyProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
